### ISSUE TITLE
Mistake in getting tokens by symbol for swaps

### ISSUE THREAD

**Issue by Nick2Nik** [RichardAtCT/1inch_wrapper#25] opened 2023-08-16 22:32 UTC
It seems they changed keys for tokens: {'0x5aea5775959fbc2557cc8789bc1bf90a239d9a91': {'symbol': 'WETH', 'name': 'Wrapped Ether', 'address': '0x5aea5775959fbc2557cc8789bc1bf90a239d9a91', 'decimals': 18,

When writing "USDT' to get swap it returns KEY_Error. While if writing USDT CONTRACT works perfectly.

Try: chain polugon
From^ MATIC
TO: USDT

**Comment by makbeta** [comment] 2023-08-16 22:43
@Nick2Nik I believe it's a duplicate of #21, which was resolved. Try pulling in v2.0.3 it should have a solution in it.

**Closed** 2023-08-18 07:33 UTC
